package com.ipaylinks.cmp.css.dal.mapper;

import com.ipaylinks.cmp.css.dal.model.MertSettlementLog;

public interface MertSettlementLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MERT_SETTLEMENT_LOG
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    int insert(MertSettlementLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MERT_SETTLEMENT_LOG
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    int insertSelective(MertSettlementLog record);
}