package com.ipaylinks.cmp.css.dal.mapper;

import com.ipaylinks.cmp.css.dal.model.MertSettlementRecord;

public interface MertSettlementRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MERT_SETTLEMENT_RECORD
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    int insert(MertSettlementRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MERT_SETTLEMENT_RECORD
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    int insertSelective(MertSettlementRecord record);
}