package com.ipaylinks.cmp.css.dal.model;

import java.math.BigDecimal;
import java.util.Date;

public class MertSettlementRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_RECORD.ID
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_RECORD.MERCHANT_ID
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    private String merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_RECORD.SETTLE_DATE
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    private String settleDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_RECORD.STATUS
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_RECORD.ORDER_TYPE
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_RECORD.TIMES
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    private BigDecimal times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_RECORD.GMT_CREATE_TIME
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    private Date gmtCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_RECORD.GMT_UPDATE_TIME
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    private Date gmtUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_RECORD.ID
     *
     * @return the value of T_MERT_SETTLEMENT_RECORD.ID
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_RECORD.ID
     *
     * @param id the value for T_MERT_SETTLEMENT_RECORD.ID
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_RECORD.MERCHANT_ID
     *
     * @return the value of T_MERT_SETTLEMENT_RECORD.MERCHANT_ID
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_RECORD.MERCHANT_ID
     *
     * @param merchantId the value for T_MERT_SETTLEMENT_RECORD.MERCHANT_ID
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_RECORD.SETTLE_DATE
     *
     * @return the value of T_MERT_SETTLEMENT_RECORD.SETTLE_DATE
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public String getSettleDate() {
        return settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_RECORD.SETTLE_DATE
     *
     * @param settleDate the value for T_MERT_SETTLEMENT_RECORD.SETTLE_DATE
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public void setSettleDate(String settleDate) {
        this.settleDate = settleDate == null ? null : settleDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_RECORD.STATUS
     *
     * @return the value of T_MERT_SETTLEMENT_RECORD.STATUS
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_RECORD.STATUS
     *
     * @param status the value for T_MERT_SETTLEMENT_RECORD.STATUS
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_RECORD.ORDER_TYPE
     *
     * @return the value of T_MERT_SETTLEMENT_RECORD.ORDER_TYPE
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_RECORD.ORDER_TYPE
     *
     * @param orderType the value for T_MERT_SETTLEMENT_RECORD.ORDER_TYPE
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_RECORD.TIMES
     *
     * @return the value of T_MERT_SETTLEMENT_RECORD.TIMES
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public BigDecimal getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_RECORD.TIMES
     *
     * @param times the value for T_MERT_SETTLEMENT_RECORD.TIMES
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public void setTimes(BigDecimal times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_RECORD.GMT_CREATE_TIME
     *
     * @return the value of T_MERT_SETTLEMENT_RECORD.GMT_CREATE_TIME
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public Date getGmtCreateTime() {
        return gmtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_RECORD.GMT_CREATE_TIME
     *
     * @param gmtCreateTime the value for T_MERT_SETTLEMENT_RECORD.GMT_CREATE_TIME
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public void setGmtCreateTime(Date gmtCreateTime) {
        this.gmtCreateTime = gmtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_RECORD.GMT_UPDATE_TIME
     *
     * @return the value of T_MERT_SETTLEMENT_RECORD.GMT_UPDATE_TIME
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public Date getGmtUpdateTime() {
        return gmtUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_RECORD.GMT_UPDATE_TIME
     *
     * @param gmtUpdateTime the value for T_MERT_SETTLEMENT_RECORD.GMT_UPDATE_TIME
     *
     * @mbg.generated Wed Aug 29 18:06:54 CST 2018
     */
    public void setGmtUpdateTime(Date gmtUpdateTime) {
        this.gmtUpdateTime = gmtUpdateTime;
    }
}