package com.ipaylinks.cmp.css.dal.model;

import java.util.Date;

public class MertSettlementLog  {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_LOG.ID
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_LOG.MERCHANT_ID
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    private String merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_LOG.TRADE_TYPE
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    private String tradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_LOG.STATUS
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_LOG.ORDER_TYPE
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    private String dealDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_LOG.RESULT
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_LOG.GMT_CREATE_TIME
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    private Date gmtCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MERT_SETTLEMENT_LOG.GMT_UPDATE_TIME
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    private Date gmtUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_LOG.ID
     *
     * @return the value of T_MERT_SETTLEMENT_LOG.ID
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_LOG.ID
     *
     * @param id the value for T_MERT_SETTLEMENT_LOG.ID
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_LOG.MERCHANT_ID
     *
     * @return the value of T_MERT_SETTLEMENT_LOG.MERCHANT_ID
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_LOG.MERCHANT_ID
     *
     * @param merchantId the value for T_MERT_SETTLEMENT_LOG.MERCHANT_ID
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_LOG.TRADE_TYPE
     *
     * @return the value of T_MERT_SETTLEMENT_LOG.TRADE_TYPE
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_LOG.TRADE_TYPE
     *
     * @param tradeType the value for T_MERT_SETTLEMENT_LOG.TRADE_TYPE
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_LOG.STATUS
     *
     * @return the value of T_MERT_SETTLEMENT_LOG.STATUS
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_LOG.STATUS
     *
     * @param status the value for T_MERT_SETTLEMENT_LOG.STATUS
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_LOG.ORDER_TYPE
     *
     * @return the value of T_MERT_SETTLEMENT_LOG.ORDER_TYPE
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_LOG.RESULT
     *
     * @return the value of T_MERT_SETTLEMENT_LOG.RESULT
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public String getResult() {
        return result;
    }

    public String getDealDate() {
		return dealDate;
	}

	public void setDealDate(String dealDate) {
		this.dealDate = dealDate;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_LOG.RESULT
     *
     * @param result the value for T_MERT_SETTLEMENT_LOG.RESULT
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_LOG.GMT_CREATE_TIME
     *
     * @return the value of T_MERT_SETTLEMENT_LOG.GMT_CREATE_TIME
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public Date getGmtCreateTime() {
        return gmtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_LOG.GMT_CREATE_TIME
     *
     * @param gmtCreateTime the value for T_MERT_SETTLEMENT_LOG.GMT_CREATE_TIME
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public void setGmtCreateTime(Date gmtCreateTime) {
        this.gmtCreateTime = gmtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MERT_SETTLEMENT_LOG.GMT_UPDATE_TIME
     *
     * @return the value of T_MERT_SETTLEMENT_LOG.GMT_UPDATE_TIME
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public Date getGmtUpdateTime() {
        return gmtUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MERT_SETTLEMENT_LOG.GMT_UPDATE_TIME
     *
     * @param gmtUpdateTime the value for T_MERT_SETTLEMENT_LOG.GMT_UPDATE_TIME
     *
     * @mbg.generated Wed Aug 29 18:08:04 CST 2018
     */
    public void setGmtUpdateTime(Date gmtUpdateTime) {
        this.gmtUpdateTime = gmtUpdateTime;
    }
}